// <auto-generated />
using System;
using APIOpportunities.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIOpportunities.Migrations
{
    [DbContext(typeof(APIOpportunitiesContext))]
    [Migration("20240606191055_Opportunities")]
    partial class Opportunities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Models.Opportunity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ErrorsQtd")
                        .HasColumnType("bigint");

                    b.Property<int>("HoursOff")
                        .HasColumnType("int");

                    b.Property<long>("HoursQtd")
                        .HasColumnType("bigint");

                    b.Property<long>("HoursSleep")
                        .HasColumnType("bigint");

                    b.Property<long>("LearnLevel")
                        .HasColumnType("bigint");

                    b.Property<string>("OutbreakLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Opportunity");
                });
#pragma warning restore 612, 618
        }
    }
}
